// Ikon Phosphor (regular) — codepoint sama dengan host/src/gui/icons.rs.
export const ICON = {
  activity: "\u{e000}",
  broadcast: "\u{e0f2}",
  check: "\u{e182}",
  clock: "\u{e19a}",
  devices: "\u{eba4}",
  dots: "\u{e1fe}",
  folder: "\u{e256}",
  gear: "\u{e270}",
  globe: "\u{e288}",
  grid_four: "\u{e296}",
  heart: "\u{e2a8}",
  keyboard: "\u{e2d8}",
  lightning: "\u{e2de}",
  list_bullets: "\u{e2f0}",
  magnify: "\u{e30c}",
  mic: "\u{e326}",
  monitor: "\u{e32e}",
  music: "\u{e340}",
  play: "\u{e3d0}",
  plus: "\u{e3d4}",
  plugs: "\u{eb56}",
  plugs_connected: "\u{eb56}",
  power: "\u{e3da}",
  qr_code: "\u{e3e6}",
  squares_four: "\u{e464}",
  stack: "\u{e466}",
  star: "\u{e46a}",
  terminal: "\u{eae8}",
  user: "\u{e4c2}",
  user_circle: "\u{e4c4}",
  video: "\u{e4da}",
  wifi: "\u{e4ea}",
  x: "\u{e4f6}",
} as const;

export type IconName = keyof typeof ICON;
